"""link coffee log to user

Revision ID: 480baee37deb
Revises: e55e7f3e21a3
Create Date: 2026-05-10 15:32:09.131416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480baee37deb'
down_revision = 'e55e7f3e21a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee_log', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_coffee_log_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coffee_log_user', type_='foreignkey')

    # ### end Alembic commands ###
