"""add message model

Revision ID: 831eef72ab26
Revises: 480baee37deb
Create Date: 2026-05-12 17:22:20.663410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831eef72ab26'
down_revision = '480baee37deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='fk_msg_receiver'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='fk_msg_sender'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coffee_log', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_coffee_log_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coffee_log_user', type_='foreignkey')

    op.drop_table('message')
    # ### end Alembic commands ###
