"""create coffee log table

Revision ID: fb5d5d07b687
Revises: 
Create Date: 2026-05-03 16:37:58.717419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5d5d07b687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_name', sa.String(length=100), nullable=False),
    sa.Column('coffee_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_logged', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee_log')
    # ### end Alembic commands ###
